version: '3'
services:
  app:
    build:
      context: ./docker/go
      dockerfile: Dockerfile
    volumes:
      - ".:/go"
    tty: true
    environment:
      - GOPATH=/go/libs
      - DB_TYPE=postgres
      - POSTGRES_DBHOST=db
      - POSTGRES_DBNAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "80:80"
    networks:
      - goliblang
  db:
    container_name: "db"
    build:
      context: ./docker/pgsql
      dockerfile: Dockerfile
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      # 永続化することでコンテナ削除してもOK
      - "govolumes:/var/lib/postgresql/data"
      - "./docker/pgsql/init:/docker-entrypoint-initdb.d"
    networks:
     - goliblang

networks:
  goliblang:
    driver: "bridge"
volumes: 
  govolumes: 